import { type NextRequest, NextResponse } from "next/server"

/**
 * Captures a channel partner's referral code from `?ref=<code>` on any page.
 *
 * A click is not a referral, so nothing is written to the database here — the
 * code sits in a cookie until the visitor actually creates an account, at which
 * point `attributeReferral()` in app/actions/referral.ts turns it into a
 * `partner_referrals` row. That keeps the table a record of real signups rather
 * than of traffic, and it means a partner cannot inflate their numbers by
 * hitting their own link.
 *
 * The cookie carries a fixed 30-day life because middleware runs on every
 * request and should not be querying Supabase for a setting. The authoritative
 * window is `referral_attribution_days` in the settings table, checked
 * server-side at signup — so shortening the window there takes effect
 * immediately, even for cookies already handed out.
 *
 * First code wins: an existing cookie is never overwritten. Otherwise the last
 * partner whose link a visitor happened to touch — including one they landed on
 * after already deciding to sign up — would take the commission.
 */

const REF_COOKIE = "bw_ref"
const MAX_WINDOW_DAYS = 30

export function middleware(request: NextRequest) {
  const code = request.nextUrl.searchParams.get("ref")?.trim()
  const response = NextResponse.next()

  if (!code || request.cookies.has(REF_COOKIE)) return response

  // Codes are generated by this application, so anything that is not a short
  // alphanumeric string is not one of ours and is not worth storing.
  if (!/^[A-Za-z0-9]{4,32}$/.test(code)) return response

  response.cookies.set(REF_COOKIE, JSON.stringify({ code, at: new Date().toISOString() }), {
    maxAge: MAX_WINDOW_DAYS * 24 * 60 * 60,
    httpOnly: true,
    sameSite: "lax",
    path: "/",
    secure: process.env.NODE_ENV === "production",
  })

  return response
}

export const config = {
  // Static assets and the image optimiser can never carry a referral link a
  // human clicked, and running on them would only add latency.
  matcher: ["/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml).*)"],
}
