import type { MetadataRoute } from "next"

import { SITE_NAME, SITE_TAGLINE } from "@/lib/seo"

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME} — ${SITE_TAGLINE}`,
    short_name: "Boliwala",
    description:
      "Search SARFAESI bank auction properties across India — reserve price, EMD, and auction dates, free to browse.",
    start_url: "/",
    display: "standalone",
    background_color: "#f7f5f1",
    theme_color: "#0A0F1C",
    orientation: "portrait-primary",
    categories: ["business", "finance"],
    icons: [
      // Generated by app/icon.tsx and app/apple-icon.tsx. `maskable` is not
      // declared: the mark is not padded for Android's safe zone, so claiming
      // it would get the gavel cropped on adaptive-icon launchers.
      { src: "/icon", sizes: "64x64", type: "image/png", purpose: "any" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png", purpose: "any" },
    ],
  }
}
